name: g15t
services:
  postgres:
    image: postgres:16-alpine
    container_name: g15-db
    ports:
      - 5432:${POSTGRES_PORT}
    volumes:
      - g15-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - g15-net
volumes:
  g15-data:
networks:
  g15-net:
